export const SpriteIconsMap = [
	'Base64Image',
	'Base64Text',
	'Certificate',
	'ColorBlind',
	'ColorPicker',
	'Cron',
	'RegexTester',
	'Extensions',
	'Gzip',
	'Hash',
	'Html',
	'ImageConvert',
	'JsonToTable',
	'JsonFormatter',
	'JsonPathTester',
	'JsonYaml',
	'JWT',
	'LoremIpsum',
	'ListComparer',
	'Markdown',
	'NumberConverter',
	'PasswordGenerator',
	'PngJpegCompressor',
] as const;
